export const FILTER = 'FILTER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_SERVER_MESSAGE = 'ADD_SERVER_MESSAGE';
export const UPDATE_VARIABLES = 'UPDATE_VARIABLES';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const HIDE_CONVERSATION = 'HIDE_CONVERSATION';
