export const UPDATE_PREDICTIONS = 'UPDATE_PREDICTIONS';
export const ADD_INPUT_HISTORY = 'ADD_INPUT_HISTORY';
export const MOVE_INPUT_HISTORY = 'MOVE_INPUT_HISTORY';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_SERVER_MESSAGE = 'ADD_SERVER_MESSAGE';
export const UPDATE_VARIABLES = 'UPDATE_VARIABLES';
export const UPDATE_HISTORY = 'UPDATE_HISTORY'; // convo history
export const HIDE_CONVERSATION = 'HIDE_CONVERSATION';
